import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'components/button/index': 'src/components/button/index.ts',
    'components/icon-button/index': 'src/components/icon-button/index.ts',
    'components/link/index': 'src/components/link/index.ts',
    'components/badge/index': 'src/components/badge/index.ts',
    'components/avatar/index': 'src/components/avatar/index.ts',
    'components/separator/index': 'src/components/separator/index.ts',
    'components/spinner/index': 'src/components/spinner/index.ts',
    'components/skeleton/index': 'src/components/skeleton/index.ts',
    'components/alert/index': 'src/components/alert/index.ts',
    'components/accordion/index': 'src/components/accordion/index.ts',
    'components/card/index': 'src/components/card/index.ts',
    'components/code-block/index': 'src/components/code-block/index.ts',
    'components/list-item/index': 'src/components/list-item/index.ts',
    'components/status/index': 'src/components/status/index.ts',
    'components/carousel/index': 'src/components/carousel/index.ts',
    'components/table/index': 'src/components/table/index.ts',
    'components/timeline/index': 'src/components/timeline/index.ts',
    'components/field/index': 'src/components/field/index.ts',
    'components/text-field/index': 'src/components/text-field/index.ts',
    'components/textarea/index': 'src/components/textarea/index.ts',
    'components/checkbox/index': 'src/components/checkbox/index.ts',
    'components/radio-group/index': 'src/components/radio-group/index.ts',
    'components/switch/index': 'src/components/switch/index.ts',
    'components/select/index': 'src/components/select/index.ts',
    'components/calendar/index': 'src/components/calendar/index.ts',
    'components/file-input/index': 'src/components/file-input/index.ts',
    'components/filter/index': 'src/components/filter/index.ts',
    'components/otp-input/index': 'src/components/otp-input/index.ts',
    'components/range-slider/index': 'src/components/range-slider/index.ts',
    'components/rating/index': 'src/components/rating/index.ts',
    'components/validator/index': 'src/components/validator/index.ts',
    'components/tabs/index': 'src/components/tabs/index.ts',
    'components/dialog/index': 'src/components/dialog/index.ts',
    'components/tooltip/index': 'src/components/tooltip/index.ts',
    'components/popover/index': 'src/components/popover/index.ts',
    'components/menu/index': 'src/components/menu/index.ts',
    'components/drawer/index': 'src/components/drawer/index.ts',
    'components/indicator/index': 'src/components/indicator/index.ts',
    'components/stack/index': 'src/components/stack/index.ts',
    'components/floating-action-button/index': 'src/components/floating-action-button/index.ts',
    'components/progress/index': 'src/components/progress/index.ts',
    'components/radial-progress/index': 'src/components/radial-progress/index.ts',
    'components/theme-controller/index': 'src/components/theme-controller/index.ts',
    'components/accessibility/index': 'src/components/accessibility/index.ts',
    'components/toast/index': 'src/components/toast/index.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  treeshake: true,
});
